name: wolff
on:
  pull_request:
    branches:
      - main
      - main-*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        otp:
          - '27.3'
          - '26.2'
        kafka:
          - '2.4'
          - '1.1'
          - '0.11'
    runs-on: ubuntu-latest
    steps:

    # Setup
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache Hex packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/rebar3/hex/hexpm/packages
        key: ${{ runner.os }}-hex-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.lock')) }}
        restore-keys: |
          ${{ runner.os }}-hex-
    - name: Cache Dialyzer PLTs
      uses: actions/cache@v4
      with:
        path: ~/.cache/rebar3/rebar3_*_plt
        key: ${{ runner.os }}-dialyzer-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.config')) }}
        restore-keys: |
          ${{ runner.os }}-dialyzer-
    # Install Erlang
    - name: Install Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: '3.24.0'

    # Compile
    - name: Compile
      run: |
        rebar3 do compile, dialyzer, edoc, xref
    # Tests
    - name: Run tests
      run: |
          ./start-kafka.sh
          make eunit || (docker compose logs; false)
